# Theme
remote_theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme

# Basics
title: Barbara Cervone
description: Personal website of Barbara Cervone
url: https://barbaracervone.org
baseurl: ""
